### ISSUE TITLE
Build all base components

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#10]
We need help getting all the base components built, anything without a user next to it is available so just let us know what your working on and we'll keep the list updated:

- [x] Avatar
- [x] Badge
- [x] Button
- [x] Basic Card
- [x] Card Footer 
- [x] Pricing Card
- [x] Store Card
- [x] Gallery Card
- [x] Container
- [x] Dropdown
- [x] Dimmer
- [x] Form
- [x] Form select button groups
- [x] Form field set
- [x] Form toggle switches
- [x] Form radios
- [x] Form checkboxes
- [x] Form custom file input
- [x] Form input group text and button appends
- [x] Form input group prepend
- [x] Form select
- [x] Grid
- [x] Header
- [x] Icon
- [x] Nav
- [x] Page
- [x] Page/Website header
- [x] Page/Website navbar
- [x] Page/Website footer
- [x] Table
- [x] Text
- [x] Alert
- [x] Progress
- [x] Stamp

**Comment by iamzjohn** [comment]
Hi, is someone doing one of this components so I could choose one, and we won't duplicate?

**Comment by burakakyol** [comment]
I can get **Pricing Card** component if you didn't start

**Comment by jonthomp** [comment]
Awesome thanks @iamzjohn @burakakyol! As far as I'm aware you are currently the only 2 working on these bits so the choice is yours!

**Comment by jonthomp** [comment]
hey @iamzjohn I've started work on the cards design demo page, how is the card footer coming along?

**Comment by burakakyol** [comment]
is **Chart** component  part of the **ChartCard** or  will we be consider it the seperate one?
BTW (if it is not too urgent) I can get  Store Card,Gallery Card and Blog Card components or we may  share them

**Comment by iamzjohn** [comment]
@jonthomp sorry for the delay, I was sick but when possible I'll PR the feature

**Comment by jonthomp** [comment]
@burakakyol I don't really think there is a Chart component on its own, however, there is the [tabler demo page of charts](https://tabler.github.io/tabler/charts.html) that we would like to replicate using our Card components and using something like [react-c3js](https://github.com/bcbcarl/react-c3js)

@iamzjohn no problem just give me a nudge as soon as it's ready and I'll merge it into the demo I'm working on

**Comment by jonthomp** [comment]
@burakakyol forgot to mention, if you do start work on those pages and components, let us know as you start work on each one just to be sure no one else is :smile:

**Comment by KhaldiAmer** [comment]
Can I contribute?

**Comment by jonthomp** [comment]
@KhaldiAmer yeah certainly! I've started creating separate issues for the items in this list, perhaps have a look at https://github.com/tabler/tabler-react/issues/63 or https://github.com/tabler/tabler-react/issues/62 ?
