### ISSUE TITLE
Add Tooltip Component

### ISSUE THREAD

**Issue by MrJarv1s** [tabler/tabler-react#114]
Tabler uses tooltips for a number of items.
For example, the media component uses tooltips:
![screen shot 2018-04-28 at 17 10 27](https://user-images.githubusercontent.com/24951944/39559037-8101ccaa-4e50-11e8-8b4b-40718de90fc7.png)

Since we are trying to get rid of bootstrap components, a component could be developed from using [react-popper](https://github.com/FezVrasta/react-popper).

**Comment by MrJarv1s** [comment]
I'd like to be assigned for this one. Cheers,

**Comment by jonthomp** [comment]
@MrJarv1s have you been able to take a look at this yet?

**Comment by MrJarv1s** [comment]
Glad you ask, I’ve just gotten back from vacation. I’ll hit the road with this early this week. I have hit a few road bumps with different libraries for tooltips, but I have a few new ideas plus I can’t wait to see the changes made to the CSS (move it to the components).

You should hear from me soon.

**Comment by jonthomp** [comment]
Awesome and hope you had a great vacation!

I've used react-popper in the Dropdown components if you want to have a look at an example of how I implemented it.

**Comment by MrJarv1s** [comment]
Thanks!
I'll have a look as soon as I merge all the new changes in my local repo.

**Comment by MrJarv1s** [comment]
Has something changed in the yarn install process? I've done a `yarn install` for both the root and example folders yet the example server report it cannot find Tabler.css in the `dist` folder. Once copied over as a test, I realized that some of the other folders are not included either (Font, Images).

Am I missing something?

**Comment by MrJarv1s** [comment]
Never mind, `yarn prepare` made it all work. I did not see that one, maybe include the requirement for `prepare` in the Readme?

**Comment by jonthomp** [comment]
Oh damn sorry about that, `yarn prepare` shouldn't be required, fix coming up!

**Comment by MrJarv1s** [comment]
![tooltip](https://user-images.githubusercontent.com/24951944/40523679-d6e31272-5fa4-11e8-9f48-d8a05f9659a2.gif)

The component works!! The arrow is giving me some issues however.
I have a number of ways to fix this, but need some guidance. 

Here are my options:

1. The best way (performance-wise) would be use a full CSS implementation, this could be implemented by a simple `left: calc(50% - 0.4rem)` for a top or bottom tooltip or a `top: calc(...)` for a left or right tooltip. However this would require one of the following:
   * Add the `left: calc(...)` to Tabler.css (involves changing the original Tabler CSS) 👎
   * Add the `left: calc(...)` to another stylesheet that would work in conjunction with Tabler.css 👍 
2. Create a new arrow sub-component which would request the parent component's width in order to place the arrow in the middle. Much like the first solution is doing, but all in react. This has a performance impact since, the width of the parent component is only available after the first draw. Requiring a re-draw for the arrow every time the tooltip is generated.

I feel like 1b is the way to go, but am not sure how you guys feel about this implementation.

Let me know!

**Comment by jonthomp** [comment]
Awesome! I would go for option 1b, that's the way we've done it in the couple of other places we've needed to add our own CSS.

**Comment by AaronCoplan** [comment]
I agree 1b seems to be the way to go!
