### ISSUE TITLE
Fix invalid declarations of type Props

### ISSUE THREAD

**Issue by MrJarv1s** [tabler/tabler-react#116]
![screen shot 2018-05-03 at 06 01 53](https://user-images.githubusercontent.com/24951944/39575390-894f88d8-4e97-11e8-8df2-d3bbe110ce6a.png)

As seen in the picture above, some files have "invalid" declaration of type Props. This is shown during pre-commit lint.

**Comment by burakakyol** [comment]
In some components, the comments cause the faults  under the prop type

**Comment by MrJarv1s** [comment]
Interesting,

FormInput seams to be raised in this situation because of the double type declaration (FormStyle and Props)
GalleryCardIconItem seams to be raised because Props is missing the `|` after the brackets as in
```jsx
type Props {
...
}
```
versus
```
type Prosp = {|
...
|}

Table might be caused by the arrays? Not too sure...

**Comment by burakakyol** [comment]
Maybe an update may requires on [this script](https://github.com/tabler/tabler-react/blob/master/scripts/propscheck.py) @AaronCoplan 
or we will find a better solution to declare prop types

**Comment by jonthomp** [comment]
Flow isn't flagging any of these for me so could potentially be down to versions as well?

I've removed the comments from NavSubmenuitem and NavItem which will hopefully fix those 2 up.

**Comment by MrJarv1s** [comment]
@jonthomp 
I get these when I call `yarn precommit`

**Comment by jonthomp** [comment]
Ah ok I see, I actually get that too, must be something in the python script like @burakakyol suggests, and it's not existing correctly which still allows commits to go through

**Comment by MrJarv1s** [comment]
```py
props = [x.strip() for x in props.replace(
        '{|', '').replace('|}', '').split(',')]
props = [x for x in props if x != '']
```
seems to be causing the issues. Since it splits at all `,` then checks if the next prop starts with `+`.

**Comment by jonthomp** [comment]
I'm happy to go with replacing that precommit script with a `yarn flow` one for now

**Comment by MrJarv1s** [comment]
Replacing the following part of the script:
```py
for prop in props:
    if not prop.startswith('+'):
        return False
```
with the following:
```py
for prop in props:
    if not prop.startswith('+'):
        if "<" in prop or ">" in prop or "//" in prop:
            return True
        return False
```
seems to work.

**Comment by AaronCoplan** [comment]
Sorry for being unresponsive, I was traveling.  @jonthomp The intention of this script was to go beyond flow and check for best practices in Props type declarations i.e. declaring props as read-only using `+` and declaring props as exact object types wherever possible via `|`.  However, there may be some exceptions to this so while #119 looks to be a great hotfix, we may want to look into removing this as a precommit hook and just running manually in the future every so often.
