### ISSUE TITLE
Build all demo pages

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#12]
- [x]  Home/Dashboard
---
Interface
- [x] Cards Design
- [x] Charts
- [x] Pricing Cards
---
Components
- [ ] Maps
- [ ] Icons
- [x] Store
- [ ] Blog
- [ ] Carousel
---
Pages 
- [ ] Profile @MrJarv1s 
- [x] Register
- [x] Login
- [x] Forgot Password
- [x] 400 error
- [x] 401 error
- [x] 403 error
- [x] 404 error
- [x] 500 error
- [x] 503 error
- [x] Email
- [x] Empty Page
- [ ] RTL mode
---
- [x] Form Elements
---
- [x] Gallery

**Comment by MrJarv1s** [comment]
Are we trying to reproduce the demo pages that are presented on `tabler`?

**Comment by MrJarv1s** [comment]
I've made a fork, I'll be working on components since I can resolve one at a time based on you guys' advancements. I've assumed a yes to my earlier question.

**Comment by AaronCoplan** [comment]
Hey - sorry for the lack of response.  Yes we are trying to build out the components in React (not necessarily matching 1:1 to the tabler repo) and then trying to replicate the demo pages.

**Comment by MrJarv1s** [comment]
Perfect, I'll try to match their component pages as seen in [tabler/dist]( https://github.com/tabler/tabler/tree/dev/dist). Now you guys seem to be working pretty hard at it (at least today), I'll do my best to get working on the demos.

**Comment by MrJarv1s** [comment]
@AaronCoplan I am trying to understand the current component layout and I see two `form` component folders in the `src` folder. One being from `src/forms` and the other one from `src/components/Form/`

I assume we'll slowly converge towards having all components in the `src/components/` and not residing in the `src/` folder. I am wrong?

**Comment by AaronCoplan** [comment]
That’s correct - I’ll probably clean up src/forms tomorrow when I combine
its functionality with the other form component

**Comment by MrJarv1s** [comment]
Excellent, I’ll assume everything originates from the component folder. 

Thanks

**Comment by jonthomp** [comment]
hey @MrJarv1s please could you let us know which demo pages you are working so we don't duplicate? And if you're working on any new components mention them over in https://github.com/tabler/tabler-react/issues/10 too?

**Comment by MrJarv1s** [comment]
@jonthomb I have finished the error pages and am currently working on the “empty” page to have something to refer to for the following ones. I have forked my work, is there an easy way for me to show you my progression?

**Comment by MrJarv1s** [comment]
@jonthomp To be a bit more precise in my message: I am working on "Pages" from the list in the issue description.

**Comment by MrJarv1s** [comment]
I've been dealing with top components since the beginning but `empty.react.js` is giving me some trouble. I'd like to call a sub-component (i.e. `DropdownMenu` instead of `Dropdown`). Is there a way to do so? I tried the following:

```js
import { DropdownMenu} from 'tabler-react';

function Empty () {
  return ( <DropdownMenu />)
}
```

and

```js
import { Dropdown } from 'tabler-react';
const { DropdownMenu } = Dropdown;

function Empty () {
  return ( <DropdownMenu />)
}
```

both these idea failed miserably... Am I supposed to use the top-level component and a specific `className`?

**Comment by AaronCoplan** [comment]
@MrJarv1s I haven't looked at these components much yet as I didn't write them but I'll take a look and try to help out

**Comment by MrJarv1s** [comment]
@AaronCoplan Thanks, but I figured it out. Not my typical way of defining React Components and Sub-components, but I like it. Helps when there is a big number of components.
Subs are called using the following pattern: `<Parent.Children>`

**Comment by AaronCoplan** [comment]
@MrJarv1s Glad to hear it!  Once you finish the empty and error pages, can you submit a pr for your work so far? 👍

**Comment by jonthomp** [comment]
@MrJarv1s thanks for updates on what you're working on, I'm going to get the form elements page up and running. 

Glad you figured out the Dropdown components 👍 . At this time the majority of ./components are very much base building blocks so there can be some level of complexity to piecing some of them together.
The plan is that we will provide more complex components built on top of these, and even more on top of those, that our end users will then use to piece their site together.

I'll try and get some notes together asap on usage instructions for the base components  we already have in there

**Comment by MrJarv1s** [comment]
@AaronCoplan @jonthomp 
I'll PR later today with the Error pages. The Empty page and how to approach it with the correct components is giving me some trouble, it will be covered in a future PR.

**Comment by MrJarv1s** [comment]
@jonthomp Any timeframe on a merge from the `form-elements-demo-page` branch? I'd love to see `Site-Wrapper.react.js` in use.

**Comment by jonthomp** [comment]
@MrJarv1s I'm just holding it back at the moment due to Form component clashes (https://github.com/tabler/tabler-react/issues/25) but I believe that is soon to be resolved, @AaronCoplan have you a rough eta on that one?

**Comment by AaronCoplan** [comment]
@jonthomp Submitting a PR in the next 15 mins

**Comment by jonthomp** [comment]
@MrJarv1s we're all done now :tada: and have a functioning demo site up and running https://tabler.github.io/tabler-react/ 
Have a look at HomePage or FormElementsPage to see SiteWrapper in action

**Comment by MrJarv1s** [comment]
@jonthomp That's sweet! I'll get to work on the pages tonight, more to follow from me early this week!

**Comment by MrJarv1s** [comment]
@jonthomp @AaronCoplan Empty and Email pages PR submitted, waiting for your comments.

**Comment by MrJarv1s** [comment]
@jonthomp could you add Profile to the Pages? I am currently working on a lot of components for that one.

**Comment by jonthomp** [comment]
@MrJarv1s awesome and done!
