### ISSUE TITLE
While running `yarn start` got 'tabler-react' does not contain an export named 'Media'. Error

### ISSUE THREAD

**Issue by Raghavsalotra** [tabler/tabler-react#137]

**Comment by AaronCoplan** [comment]
@Raghavsalotra sorry to hear that!  Can you do me a favor and give me the following info so I can help debug:

1. Output of `git log` so I can see what commit you are on.  Alternatively, run `git pull` and try again with the latest updates.
2. Did you run `yarn install` in both the root directory of the repository and in the `examples` directory?
3. Any other info you could provide on how to reproduce would be really helpful - I just tried a fresh install and couldn't reproduce the issue

**Comment by Raghavsalotra** [comment]
@AaronCoplan 

1. Please find below output of git log:
`commit bae1dbb5141dcb8694d191b3a82aa621e99d808c
Merge: 8ce202c b0bea1a
Author: Aaron Coplan <AaronCoplan@users.noreply.github.com>
Date:   Tue May 8 04:27:32 2018 -0400

    Merge pull request #132 from tabler/missing-component-documentation-pages

    Missing component documentation pages

commit 8ce202cd24764c9e724f7f48a213f8c462bb6d90
Merge: 421ffa3 732817d
Author: Aaron Coplan <AaronCoplan@users.noreply.github.com>
Date:   Tue May 8 04:24:15 2018 -0400

    Merge pull request #133 from tabler/react-styleguidist

    Auto-generating documentation powered by react-styleguidist`

2. Yes I did Yarn install in both root as well as example dir.
3. I just cloned the project and followed instruction in Readme.md .

**Comment by AaronCoplan** [comment]
Perhaps only run `yarn start` in the example dir, don't run it in the root dir in a separate terminal window.  Instead, run `yarn build` in the root dir, then once that finishes run `yarn start` in the example dir.  Let me know if that helps!

**Comment by Raghavsalotra** [comment]
@AaronCoplan  That did not help.
PFA of error i am getting.
![screen shot 2018-05-08 at 6 44 41 pm](https://user-images.githubusercontent.com/4475839/39759308-fbda8e0a-52ef-11e8-8edd-be58423a960c.png)

**Comment by burakakyol** [comment]
I guess, @Raghavsalotra  tried to import into his own project. NPM module does not contain Media component

**Comment by jonthomp** [comment]
Thanks @burakakyol you might be right there. @Raghavsalotra I've just published v0.0.4 to npm, please can you give that a try?

**Comment by Raghavsalotra** [comment]
Thanks for help team, It worked. :)
