### ISSUE TITLE
Deprecate documentation pages

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#158]
With the new documentation pages, it might be a good idea to get rid of the old pages so that people stop adding to them and are forced to write documentation for the new system.

**Comment by AaronCoplan** [comment]
@jonthomp Let me know your thoughts on this one

**Comment by jonthomp** [comment]
@AaronCoplan that's a yes from me. Have you spotted any components in particular that are in the old but not in the new that we need to resolve before deprecating the old?

**Comment by AaronCoplan** [comment]
@jonthomp I haven't had the chance to go through and compare, I'll give that a go when I get the chance

**Comment by jonthomp** [comment]
I've taken a look too, only things I could find are colors and charts documentation. Charts aren't actually our components so we can probably ignore that and I think colors will need to be done in a totally different way with the new docs system.

**Comment by AaronCoplan** [comment]
Ok cool, I guess this one is blocked on #135 and that should be it!  I'll get to work on that once I get off this next flight

**Comment by AaronCoplan** [comment]
Let's wait on this until #170 is resolved.

**Comment by MrJarv1s** [comment]
@AaronCoplan @jonthomp  #170 is resolved and so is #135, what is the next step for this?

**Comment by jonthomp** [comment]
@MrJarv1s just removing all the old documentation files from the example site (and anything that else that will no longer be needed)

**Comment by MrJarv1s** [comment]
@jonthomp So just a clean up of the example site then? Should that still be blocked?

**Comment by jonthomp** [comment]
@MrJarv1s yeah, and nope should not as far as I'm aware
