### ISSUE TITLE
Look into usage of `children?` in almost all components

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#17]
Composition is great, but there are some cases where it might be better to change `children?: React.Node` to be `title: string` or something along those lines.  It seems almost all of the components we have built take children, and I don't think they all necessarily need them.

**Comment by jonthomp** [comment]
I would potentially say both? Having the generic `children?: React.Node` provides almost unlimited flexibility for more advanced use cases.
For example, if you wanted to pass in a title that has a word highlighted in the middle, but the prop restricts you to a string, you couldn't do something simple like `<Component title={<>My <span className='highlight'>highlighted</span> word<>} />`

**Comment by AaronCoplan** [comment]
Sounds good to me!  As long as we are making sure we aren't using it in components that don't take children (such as for instance a `<TextInput>` then this sounds good 👍

**Comment by jonthomp** [comment]
Agreed, I hopefully already spotted and removed all of those situations in my last commits to https://github.com/tabler/tabler-react/pull/8
