### ISSUE TITLE
Site Header Source Code

### ISSUE THREAD

**Issue by Thomas-Smyth** [tabler/tabler-react#174]
Currently, the Site Header component includes a button that links to this repo. I understand why this button is in for the demo, documentation, etc., however, it has been added to the repo's component code and thus as a developer trying to use this repository for my own projects it is very hard for me to easily personalise your Site Header. 

I am not sure if I'm missing something, but this does not seem like a good idea to have been done.

**Comment by AaronCoplan** [comment]
@Thomas-Smyth I agree with you, we'll take care of this soon

**Comment by jonthomp** [comment]
@AaronCoplan you got this or am I ok to go ahead and fix it while working on bits atm?

**Comment by Thomas-Smyth** [comment]
Also on another slightly related note. I assume that the Site.Footer is not yet complete?

That has the same issue, but there is also no way of editing the links, etc.

**Comment by AaronCoplan** [comment]
@Thomas-Smyth I've opened #177 for the site footer so we can track the two separately
