### ISSUE TITLE
Add Font Awesome and Flags icons

### ISSUE THREAD

**Issue by Zarkus13** [tabler/tabler-react#181]
Font Awesome and Flags icons are in the demo page, but not in tabler-react.

For now, there is only Feather icons.

**Comment by jonthomp** [comment]
@Zarkus13 I will update the docs to reflect this but currently, you need to include font-awesome yourself

The flag icons should be included in the distributed package, please can you try installing the latest version and double check they are not working?

**Comment by Zarkus13** [comment]
@jonthomp you're right sorry, flags and payments icons are ok ;) Thanks !
