### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by AmirGh72** [tabler/tabler-react#193]
when used AccountDropdown or Nav.Item this error was occured:
ERROR:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `Manager`

**Comment by AaronCoplan** [comment]
@jonthomp Assigning you because you have more familiarity with these components than me.

**Comment by jonthomp** [comment]
Hi @AmirGh72 please could you provide me with an example of how you are trying to use them?

**Comment by AmirGh72** [comment]
`
import React from 'react';
import { AccountDropdown } from "tabler-react";

class Test extends React.Component {

    render() {
        return(
            <AccountDropdown
                avatarURL="#"
                name="AAA"
                description="Administrator"
                options={[
                    "profile",
                    { icon: "settings", value: "Settings", to: "/settings" },
                    "mail",
                    "message",
                    "divider",
                    "help",
                    "logout",
                ]}
            />
        );
    }
}

export default Test;
`

**Comment by jonthomp** [comment]
@AmirGh72 I haven't been able to reproduce this, which version of React are you using?

**Comment by AmirGh72** [comment]
react@16.3.1

**Comment by jonthomp** [comment]
@AmirGh72 no luck yet, I thought it might have been our usage of `React.Fragment` or something else to do with newer React version.

Are you able to share your repository with me so I can clone it and take a look? Or any further details or error message if details if any.

**Comment by AmirGh72** [comment]
it works with react@16.2.0 :)
why dosnt work with react@16.3.1 ?

**Comment by jonthomp** [comment]
@AmirGh72 I've created a branch using 16.3.1 [here](https://github.com/tabler/tabler-react/tree/react-16.3.1) and all seems to be ok, does it work for you?

**Comment by kibernetika** [comment]
It's import problem. When I used:
