### ISSUE TITLE
SCSS or LESS original files.

### ISSUE THREAD

**Issue by SalahAdDin** [tabler/tabler-react#197]
I discovered this project today and i fell in love.

I want to know if we can access to the styles core in order to modify, remove or extend the styles according to our needs.

Thanks.

**Comment by jonthomp** [comment]
Hey @SalahAdDin we don't yet use the original SCSS files in the react library, we're just using the built .css file. It might make sense for this to change, happy to take a PR if you would like to work on it?

You can find the core SCSS files [here](https://github.com/tabler/tabler/tree/dev/src/assets/scss) in the main Tabler repository.

**Comment by SalahAdDin** [comment]
@jonthomp Ok, i will do it in the comming weeks.
