### ISSUE TITLE
Empty date picker

### ISSUE THREAD

**Issue by jaydensmith** [tabler/tabler-react#202]
Is a date-picker that will allow an empty/null value something that is on the cards?

**Comment by jonthomp** [comment]
Hey @jaydensmith I'll see about adding empty/null ability to our existing simple date picker if that's the sort of thing you need?

**Comment by jaydensmith** [comment]
@jonthomp I think it would be great, as currently a null value raises an error 😄

**Comment by jonthomp** [comment]
This is a little tricker than I anticipated due to the internals of the component but I'll have another poke at it tomorrow

**Comment by bhaskesaravanan** [comment]
In the Form.Datepicker how to set the particular date. I tried with a defaultDate property. But It is now working for me

**Comment by jonthomp** [comment]
Fixed in version 2
