### ISSUE TITLE
Name and value attributes not added to select

### ISSUE THREAD

**Issue by jaydensmith** [tabler/tabler-react#206]
My example below doesn't function as expected as the name and value are not passed to the underlying select element.
```JSX
<Form.Select name="TaxFeeType" onChange={this.handleChange} value={event.TaxFeeType}>
    <option value={null}>Tax Disabled</option>
    <option value="GST">GST</option>
    <option value="VAT">VAT</option>
</Form.Select>
```

**Comment by jonthomp** [comment]
Thanks for the report, I'll have that fixed up in a few hours

**Comment by jonthomp** [comment]
These and loads more Form related bits and pieces coming up in #207
