### ISSUE TITLE
Missing CSS files, possibly a build issue

### ISSUE THREAD

**Issue by ecoleman** [tabler/tabler-react#224]
The following css imports are used, but are not available in a built version:

- `import "./Table.css";` in `(tabler-react/dist/components/Table/Table.react.js.flow:5:8)`
- `import "./Tabs.css";` in `(tabler-react/dist/components/Tabs/Tabs.react.js.flow:9:8)`
- `import "./Tooltip.css";` in `(tabler-react/dist/components/Tooltip/Tooltip.react.js.flow:7:8)`

**Comment by jonthomp** [comment]
In the built version those CSS files are compiled into the build itself so they should still be applied to your components. These errors are just coming from our automatically exported flow types (using [flow-copy-source](https://github.com/AgentME/flow-copy-source)), I'll have an investigation of a solution.
