### ISSUE TITLE
Why very slowly works?

### ISSUE THREAD

**Issue by Kalyskin** [tabler/tabler-react#228]
Why very slowly works?
not only my project.
Official page also slowly working 
https://tabler.github.io/tabler-react/
https://tabler.github.io/tabler-react/documentation/

In navbar dropdown slowly opening and when i open documentation page browser slows down

**Comment by justinglibert** [comment]
I can confirm that the demo page is indeed really slow

**Comment by rishson** [comment]
Chrome devTools shows CPU at 100% - constantly.
Without user interaction, the page is constantly calling `requestAnimationFrame` repeatedly.

You might want to check `react-popper` usage in this repo, as `v1.10.0` was constantly getting offset dimensions for the `Popper`, causing 100% CPU usage. This does not appear to still be an issue (on the demo pages linked to above), but something else is thrashing..

**Comment by AaronCoplan** [comment]
I agree it seems to be something with perhaps `requestAnimationFrame` or `Recalculate Style`.  I will try to look into this some more in the next day or two.

**Comment by rishson** [comment]
So, in `v1.10.0`, it *looks* like it is the constant recalc fo offsets/dimensions  for `popper-react`.
If I comment out my usages of `<Dropdown>`, ny CPU falls from 100% to 0%

Some weirdness [here](https://github.com/tabler/tabler-react/blob/master/src/components/Dropdown/DropdownMenu.react.js#L56) maybe?

**Comment by jonthomp** [comment]
@rishson spot on, fix coming right up!

**Comment by philiiiiiipp** [comment]
Is this already live on the demo page? I am still having extremely slow performance, both FF and Chrome.

**Comment by jonthomp** [comment]
@philiiiiiipp oops sorry about that, the demo page had not been updated, it has now!

**Comment by MrJarv1s** [comment]
That is great to know, thanks @jonthomp
