### ISSUE TITLE
SiteWrapper component dosnt work correctly !!!

### ISSUE THREAD

**Issue by AmirGh72** [tabler/tabler-react#238]
When using SiteWrapper, AccountDropdown component dosnt work. but AccountDropdown works correctly when using it separately!

**Comment by jonthomp** [comment]
Hey @AmirGh72 can you provide any more detail? What is the specific issue you are having? Some screenshots and/or code examples would be a great help too

**Comment by kelyvin** [comment]
I am actually running into the same issue. The issue occurs with the collapsed submenu when the screen width is "mobile". When you switch to a mobile screen width, the submenu gets collapsed, and we're expecting to be able to click the hamburger icon to open it. However, it does not drop down the submenu as expected. See the attached gif. 


![dropdown_issue](https://user-images.githubusercontent.com/1530102/41755031-215bde6a-758a-11e8-9dc9-d4f5041e3f4e.gif)

Thanks!

**Comment by ecoleman** [comment]
The mobile version of the navigation currently requires that you include bootstraps javascript. See https://github.com/tabler/tabler-react/blob/1e154226db7468d4b6952ed3e01fb09cddd020cc/example/src/App.react.js#L50
