### ISSUE TITLE
Responsive table breaks on small screens

### ISSUE THREAD

**Issue by philiiiiiipp** [tabler/tabler-react#263]
Hey, 

The is an issue with the responsive tables on small screens. 

<img width="535" alt="screen shot 2018-07-04 at 22 29 12" src="https://user-images.githubusercontent.com/1035746/42293378-209b0da2-7fda-11e8-9a49-b0afbbe1c134.png">

I think the culprit is the additional 

```
.table-responsive {
  overflow-x: inherit !important;
}
```
in the Table.css.

Weirdly this seems to be fixed in the current version of the live preview, but not on the code. I will do a pull request for it, but I have the feeling you already fixed it yourself :-).

**Comment by philiiiiiipp** [comment]
Sorry, its not fixed on https://tabler.github.io/tabler-react/ I was checking the main website.

**Comment by jonthomp** [comment]
It is now!
