### ISSUE TITLE
Dropdowns without buttons are broken

### ISSUE THREAD

**Issue by Superjo149** [tabler/tabler-react#272]

**Comment by jonthomp** [comment]
Hi @Superjo149 could you post a few more details like the errors you are seeing and a code example and/or screenshot?

**Comment by Superjo149** [comment]
The docs are currently broken but you can test it there, the basic dropdown doesn't work and it also doesn't log anything.

![image](https://user-images.githubusercontent.com/4314204/43383986-ec581e24-93dc-11e8-9d05-35ab12fd0a18.png)

The button variant underneath does work.

**Comment by sampsasaarela** [comment]
I have the same issue in my app. Dropdowns are not working in the [doc examples](https://tabler.github.io/tabler-react/documentation/#dropdowntriggerreact) either. I also tested plain [example](https://github.com/tabler/tabler-react/tree/master/example) and dropdowns not working. Only dropdowns in header and navigation are working.

I think that dropdowns are not initialized by bootstrap after initial rendering.

**Comment by GregoryHamel** [comment]
Thanks for submitting you problem, I’ll have a look soon about this issue.

Sadly dropdown do not use Bootstrap, they are made with popper in an effort to move to react-based components

**Comment by joseraul** [comment]
Any news about it?

**Comment by AaronCoplan** [comment]
@Superjo149 @sampsasaarela @joseraul 

I've merged in #315 which should hopefully address this.  Please see https://github.com/tabler/tabler-react/blob/95abc5875ef669271c6e2ed47b8fcbf6861adb65/example/src/HomePage.react.js#L560 for an example of how to use the Dropdown.

I'm going to close this issue, but please feel free to comment with any related issues and I will gladly reopen!
