### ISSUE TITLE
The online documentation is empty

### ISSUE THREAD

**Issue by PatrykRyba** [tabler/tabler-react#286]
Hi all,

I have read through the documentation no problem yesterday (https://tabler.github.io/tabler-react/documentation/). However, trying to read it again, as of around 9pm yesterday it won't load at all. Completely blank, nothing in source code either. Tried on three devices and two separate networks just to make sure.

Cheers.

Edit1: the console outputs "Loading failed for the <script> with source “https://tabler.github.io/tabler-react/documentation/build/bundle.d8db5f20.js”."

**Comment by jonthomp** [comment]
@PatrykRyba they're back up and running now 👍
