### ISSUE TITLE
Override themes of bootstrap

### ISSUE THREAD

**Issue by aisensiy** [tabler/tabler-react#288]
The bootstrap website provide some method to overwrite the default themes here: [https://getbootstrap.com/docs/4.1/getting-started/theming/](https://getbootstrap.com/docs/4.1/getting-started/theming/)

So is it possible to override the themes of tabler like that?

**Comment by aisensiy** [comment]
Is there some one have solution for this?

**Comment by jonthomp** [comment]
@aisensiy it's not possible to do it with `tabler-react` as we just use the compiled CSS from the main `tabler` repo. You would need to clone `[tabler](https://github.com/tabler/tabler/)` and then [adjust the variables](https://github.com/tabler/tabler/blob/dev/src/assets/scss/_variables.scss) and build the CSS to import alongside `tabler-react`.

**Comment by yatsyk** [comment]
I think it will be possible after merging of this pull request https://github.com/tabler/tabler/pull/57 .

**Comment by yatsyk** [comment]
> Is there some one have solution for this?


`npm install https://github.com/beeman/tabler.git#beeman/variable-asset-path --save`

```
//style.scss in your project
$tabler-base: "../node_modules/tabler-ui/src/assets";
@import '../node_modules/tabler-ui/src/assets/scss/variables';

//your changes 

@import '../node_modules/tabler-ui/src/assets/scss/dashboard/bootstrap/bootstrap';
@import '../node_modules/tabler-ui/src/assets/scss/dashboard/dashboard';
```
