### ISSUE TITLE
Add autocomplete on|off option to form|input elements

### ISSUE THREAD

**Issue by philiiiiiipp** [tabler/tabler-react#289]
This would be great to have. I would make a pull request if wanted.

**Comment by AaronCoplan** [comment]
@philiiiiiipp Sorry for taking so long to reply - if you wanted to work on this that would be awesome!

**Comment by GregoryHamel** [comment]
@philiiiiiipp, I'd like to know if you are working on this? Otherwise, I'd implement the change.

Cheers,

**Comment by philiiiiiipp** [comment]
Hey, i have implemented that already quite some time ago but forgot to make a pull request. 

I created it now https://github.com/tabler/tabler-react/pull/368 but there are some merge issues I believe.

Maybe its easier to just close mine and do one yourself.

**Comment by jonthomp** [comment]
Fixed by https://github.com/tabler/tabler-react/commit/bdd8f0cc2b66db1f89cf77b7ece22c128ff8e32a
