### ISSUE TITLE
SSR rendering

### ISSUE THREAD

**Issue by makstr** [tabler/tabler-react#291]
This might be related to my setup (running with next.js) but I am having issues rendering Tablet on the server. Has anyone had any success with SSR here?

**Comment by makstr** [comment]
this was an issue with my css loader, resolved

**Comment by Coriou** [comment]
Hey man. Sorry to dig this up, but I'm having troubles configuring my loader with Next too. Would you mind sharing your relevant settings please ? Thanks 🙏
