### ISSUE TITLE
Resolve bugs and warnings from browser console (React.StrictMode)

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#324]
`React.StrictMode` gives console warnings as does compiler when example project is started.  We should seek to resolve all of these warnings and errors.

![screen shot 2018-10-07 at 4 46 53 pm](https://user-images.githubusercontent.com/9311453/46586745-c7052e00-ca50-11e8-9b3d-cf2629cdcb33.png)
<img width="1369" alt="screen shot 2018-10-07 at 4 48 00 pm" src="https://user-images.githubusercontent.com/9311453/46586746-c7052e00-ca50-11e8-884c-a5d3e6a2f6d7.png">

**Comment by GregoryHamel** [comment]
The source of the problem is probably shared with #292.

**Comment by AaronCoplan** [comment]
@GregoryHamel Agreed - I also think that anything resolving this will also address #292.  Do you know where the staticcontext prop is coming from?  Is that related to routing or popper?

**Comment by AaronCoplan** [comment]
@GregoryHamel Any update on this?  Hoping to close #292 soon

**Comment by treyhakanson** [comment]
Is there any update on this? If not, I'd be open to working on this

**Comment by GregoryHamel** [comment]
@treyhakanson Please go ahead! I really haven't had the chance to look into this any further...

**Comment by jonthomp** [comment]
Closing as this has now been completed in version 2
