### ISSUE TITLE
Dropdown component using the component children format doesn't work

### ISSUE THREAD

**Issue by jdelrosarioo** [tabler/tabler-react#325]
Using the component props, the dropdown works as expected. But when using the children format the items doesn't show. It doesn't even render in the markup.

**Comment by AaronCoplan** [comment]
@jdelrosarioo Currently the children format does not work and the component props are the preferred method.  Do you have a use case that requires the children format?  If not, I will likely simply remove that from the documentation.

**Comment by jdelrosarioo** [comment]
I think if all the props of the dropdown item could be provided then yes. But putting all of these as the dropdown props is a bit verbose don't you think?

**Comment by jonthomp** [comment]
Fixed in the WIP version 2
