### ISSUE TITLE
Help with Site.Header

### ISSUE THREAD

**Issue by ducanh2110** [tabler/tabler-react#337]
I am using Site.Header and when I test on mobile device I dont have collapse menu button like Site.Wrapper so I need to create my own togglerIcon button. And to make it work I need to find Nav div by className and sometimes I think it wont work correctly. Please help me. Thanks

**Comment by AaronCoplan** [comment]
@ducanh2110 Your question doesn't provide much detail - can you give a little more insight into what exactly you are doing and why you think it won't work correctly?

**Comment by ducanh2110** [comment]
@AaronCoplan when I'm using SiteWrapper components, there's already a toogle menu button when I resize to mobile. But If I'm using Site.Header now there's not  a toogle menu button. Help me with this. Thanks

**Comment by chubaka** [comment]
Fixed, added this pull request for review:
https://github.com/tabler/tabler-react/pull/344

**Comment by GregoryHamel** [comment]
@ducanh2110 I believe you are looking for this, correct?
![screen shot 2018-11-12 at 12 33 51](https://user-images.githubusercontent.com/24951944/48364829-697b8700-e677-11e8-9f7b-8290783e6335.png)

If so, this is the `Site.Nav` component. It takes all the navigation items found in the non-mobile version of the page and puts it in the toggle button. If you want this to be active at all time, I'd consider giving it the `collapsed` prop at all times.

**Comment by ducanh2110** [comment]
@GregoryHamel yes, it's exactly what i want

**Comment by GregoryHamel** [comment]
Can you provide us with a sample of your code so we can have a look?
You're probably pretty close to it and are just missing a little something.

**Comment by ducanh2110** [comment]
It's been long time and I don't remember where the project locate, but I'm
sure that when I used SIte.Nav there's no Collapse button

**Comment by AaronCoplan** [comment]
Going to close this for lack of details.  Feel free to comment if it needs to be reopened.
