### ISSUE TITLE
How to access to the value of Form.DatePicker?

### ISSUE THREAD

**Issue by alejandrofloresm** [tabler/tabler-react#338]
Hi!

How can I access to the value of Form.DatePicker? I have tried setting it up a "name" attribute to the component but that's doesn't work. 

My form looks like this:

```html
<Form.Group label="Email" isRequired="true">
  <Form.Input name="user[email]" />
</Form.Group>

<Form.Group label="Created on" isRequired="true">
  <Form.DatePicker
    defaultDate={new Date()}
    format="dd/mm/yyyy"
    maxYear={2018}
    minYear={1897}
  />
</Form.Group>
```

And normally I'm getting the values as:

```javascript
let user = {};
user.email = event.target.elements['buyer[email]'].value;
```

How can I access to the value of Form.DatePicker?

I can get the value using the onChange option but if the user doesn't change the date then I can not get that value.

Thanks for all the hard work!

**Comment by jonthomp** [comment]
Closing this, but in case anyone does come back here - this is a limitation in the version 1 implementation, the only way to get the value is using the `onChange` prop.
This has changed in v2 which allows you to pass props down to the 3 `select` elements/
