### ISSUE TITLE
Flow error with TimelineItemTitle

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#353]
See attached image - this has been here for a while and we should seek to resolve it for good.

<img width="843" alt="screen shot 2018-11-11 at 11 16 32 am" src="https://user-images.githubusercontent.com/9311453/48315365-51d2ce80-e5a3-11e8-8335-53c0b08d8052.png">

**Comment by GregoryHamel** [comment]
I have a PR coming for this one. Few fixes including some browser warnings. Should be in by the end of the day.
