### ISSUE TITLE
Attempted import error: 'NotificationTray' is not exported from 'tabler-react'.

### ISSUE THREAD

**Issue by 12jm** [tabler/tabler-react#357]
Trying to use NotificationTray component and throws this error

**Comment by GregoryHamel** [comment]
@12jm have you tried importing `Notification.Tray`? 
Its export reflects the hierarchy of the components, since `NotificationTray` is a child of the `Notification` component it can only be imported as `Notification.Tray`

**Comment by 12jm** [comment]
Thanks @GregoryHamel. It worked!

Importing this way:
>> Import { Notification } from "tabler-react"

and used in this way:    
          
            <Notfication.Tray
                 ...
             />

Instead of :
          
           <NotficationTray
                 ...
           />
