### ISSUE TITLE
How to add options to Form.Select?

### ISSUE THREAD

**Issue by 12jm** [tabler/tabler-react#359]
Form.Select doesn't have demo on how to add options

**Comment by AaronCoplan** [comment]
If you go to [this page](https://tabler.io/tabler-react/form-elements) on the demo and click the "Source" button for Select it will give you the following:

![screen shot 2018-11-13 at 11 48 54 pm](https://user-images.githubusercontent.com/9311453/48460813-c32aa100-e79e-11e8-8e65-7d992aa35502.png)

Hope that helps!  Feel free to follow up with any more questions.

**Comment by ebarahona** [comment]
<Form.Group label="Countries">
    <Form.Select>
    {countries
    .map((item, index) => (
        <option
          key={index}
          value={item}
          onChange={handleChange}
        >
        {item}
        </option>
    </Form.Select>
    </Form.Group>
    
    
// Somewhere
const countries = ["UK", "Germany"];
