### ISSUE TITLE
documentation is not work

### ISSUE THREAD

**Issue by vladimirfriptu** [tabler/tabler-react#360]
Thanks for your work, I would like to try your creation, but I can’t get to the documentation page.

**Comment by Romainpetit** [comment]
+1, It's been down for the last 24h

**Comment by AaronCoplan** [comment]
@vladimirfriptu @Romainpetit Sorry about that!  I just put it back online - try hard reloading https://tabler.io/tabler-react/documentation/

**Comment by Romainpetit** [comment]
Thanks @AaronCoplan !

**Comment by NickAlvesX** [comment]
It's happening again.

**Comment by AaronCoplan** [comment]
Should be resolved now.  Very sorry to those impacted.
