### ISSUE TITLE
NavItem Active State Faulty

### ISSUE THREAD

**Issue by Thomas-Smyth** [tabler/tabler-react#361]
Hello all,

It seems that the active states of `NavItems` are being incorrectly set when using react-router.

No need to supply my own code to show this as the issue is present in the [example ](https://github.com/tabler/tabler-react/tree/master/example)section of this repository.

When most pages are being accessed, it shows both the Home page and the currently selected page as active. For example, in [this](https://tabler.io/tabler-react/gallery) gallery page, both the Gallery page `NavItem` and the Home page `NavItem` are active.

To me, without analysing the repository code, it looks as if the system to show which `NavItem` is active checks the `NavItem` paths to see if they **contain** the current path. I do not believe this should be the case as it causes paths such as `/` and `/blog` to both be shown as active when only one should be active at a time. However, this should be the case for all sublinks / links in the dropdowns from the navbar.

**Comment by GregoryHamel** [comment]
@Thomas-Smyth thanks for looking into this. It’s been on my list of things to look at for a while. I’ll have a look and report back soon.

**Comment by Thomas-Smyth** [comment]
Done some more experimenting, it seems that the active state is being passed correctly to the `Nav.Link` component, but it's children something goes wrong. That seems to do with React Router's `exact` prop not being present.

![Issue](https://i.gyazo.com/9bc5f45c487e1779c3026a130161e210.png)
