### ISSUE TITLE
Form.Datepicker does not change default value 

### ISSUE THREAD

**Issue by quangcuong0808** [tabler/tabler-react#366]
`<Form.DatePicker
                                defaultDate={date}
                                format="mm/dd/yyyy"
                                maxYear={2200}
                                minYear={1970}
                                onChange={(e) => this.onHandleChangePicker('startDate', e)}
                                monthLabels={[
                                    'January',
                                    'February',
                                    'March',
                                    'April',
                                    'May',
                                    'June',
                                    'July',
                                    'August',
                                    'September',
                                    'October',
                                    'November',
                                    'December'
                                ]}
                                //className="date-picker-isDisabled"
                            />`
I try to change default value but it only change when I refresh page  , OR when **date** is 1, picker show max date,  then **date** change to 2, picker show 1

**Comment by AaronCoplan** [comment]
The intended behavior of `Form.DatePicker` is that the `defaultDate` prop is the initially rendered date.  When you change the `defaultDate` prop, it will not cause a re-render because that is simply passed to the initial state.

Can you clarify a little more about the picker showing max date when date is 1 or showing 1 when it changes to 2?
