### ISSUE TITLE
Keep CSS in sync with tabler/tabler?

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#372]
#365 has modified our CSS - we should diff our CSS file with the latest on [tabler/tabler](https://github.com/tabler/tabler) and see if there are any changes we should make.

**Comment by GregoryHamel** [comment]
@AaronCoplan I think we should keep css differences at the component level instead of changing the actual tabler CSS (see the Tooltip Component for an example). This would allow us to keep on pulling the actual CSS from tabler. What do you think?

**Comment by jonthomp** [comment]
Closing because this is now implemented on the version 2 branch
