### ISSUE TITLE
It is not clear which notifications in a notifications tray are unread

### ISSUE THREAD

**Issue by mattsoftware** [tabler/tabler-react#376]
When listing the notifications in the tray it is not clear which ones have been read and which ones not. Passing down if a message is unread or not should not be a big deal, but how do we indicate in the interface which ones?

Should we simply provide a className on the notification and style it to be a light blue background or something that fits the theme well?

We could also use the red dot, or bold the text but the different coloured background seems to be more industry standard.

Thoughts?

**Comment by GregoryHamel** [comment]
@Mattsoftware, I see what you are saying, but when looking at the Tabler demo, it isn’t really implemented either.
Maybe the notification were always supposed to be unread only.
I’m sure you could add a `color` prop to the notification component and add a `color-primary` or `color-secondary` class for unread. Have a look and see if that works for you. I haven’t tested it on my end, but that’s the first thing that comes to mind.

**Comment by AaronCoplan** [comment]
I'm open to deviating from the Tabler demo in some aspects, but if we do, we should keep a document with the differentiations somewhere.  However, another alternative is to provide an optional property `isRead?: boolean`.  Then if people wanted a shorthand way to do it they could use our `isRead` property, or if they wanted to customize it they could utilize the `className` property.

**Comment by mattsoftware** [comment]
OIC... @GregoryHamel that makes sense. 

Pondering my previous pull request, @AaronCoplan , do you think we can drop the unread property from the notification tray altogether. The unread property can be inferred based on the notificationsObjects.length property. It will then be more obvious what this section is for, basically only unread notifications rather than a mixture of all notifications any of which can be read or unread.

**Comment by GregoryHamel** [comment]
Ok, so I've been thinking about this a little bit tonight... There has to be a reason for the _new notification_ red dot, which would probably mean that there should be a way to differentiate between old and new notifications. Now I tried adding a `bg-light` class and it doesn't look too bad for a different notification look. Have a look:
![screen shot 2018-11-29 at 20 39 41](https://user-images.githubusercontent.com/24951944/49263163-573f6e00-f417-11e8-9f05-373ba40f0c28.png)

**Comment by mattsoftware** [comment]
I agree, that looks great to me.... but my guess is the dot is literally meant to say, "look at me, theres something in here" (otherwise it would be a badge with the number of unread, yea?)

So I am thinking no dot = no notitifications, red dot = notifications, mark all as read = make all notifications go away

But I am happy either way, as long as its clear :)

**Comment by AaronCoplan** [comment]
I think we should keep the unread property - this gives project's using our package the flexibility to decide for themselves whether to only show unread notifications or all notifications in the tray.

**Comment by mattsoftware** [comment]
Fixed with https://github.com/tabler/tabler-react/pull/378

Thank you
