### ISSUE TITLE
Documentation link broken and Demo site down

### ISSUE THREAD

**Issue by zkynet** [tabler/tabler-react#385]
https://r.tabler.io/tabler-react/documentation/

It seems some of your documentation links are broken. 

Additionally the tabler-react demo link seems to be having https certificate issues.

**Comment by GregoryHamel** [comment]
Raised an issue with Tabler see [Issue #232](https://github.com/tabler/tabler/issues/232)

**Comment by AaronCoplan** [comment]
Documentation should be back online, http://tabler-react.com/
