### ISSUE TITLE
Toggler is not working

### ISSUE THREAD

**Issue by Jatapiaro** [tabler/tabler-react#391]
The Toggler component is not working. I have to use the old switch component to make it work, but that leads to the problem that the style is not loaded.

**Comment by Thomas-Smyth** [comment]
Maybe provide a sample of your code? Seems to be working for me...

[![Image from Gyazo](https://i.gyazo.com/853eca29df55c14361c5938f19108470.gif)](https://gyazo.com/853eca29df55c14361c5938f19108470)

**Comment by AaronCoplan** [comment]
Agreed with @Thomas-Smyth , a code sample would be appreciated :)

**Comment by Jatapiaro** [comment]
It was my mistake, another css component was overriding the Form.Switch. Sorry
