### ISSUE TITLE
Refactor filenames to end with .react.js or .js depending on functionality.

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#4]

**Comment by maracuja-juice** [comment]
Why not make this with folders instead? (like a components folder and a util folder.)

**Comment by AaronCoplan** [comment]
The primary motivation for doing it this way is so it is also very clear which type something is when you are importing i.e. `import Form from './Form.react';` vs `import nullthrows from ./nullthrows;`

**Comment by jonthomp** [comment]
Everything is renamed now
