### ISSUE TITLE
Windows Precommit

### ISSUE THREAD

**Issue by Thomas-Smyth** [tabler/tabler-react#402]
The current `precommit` script calls the command `./scripts/runflow`. This is not supported by windows, which means for every commit this has to be run manually and then committed with the `--no-verify` flag.

Would be nice to get this resolved.

**Comment by Thomas-Smyth** [comment]
[![Image from Gyazo](https://i.gyazo.com/755e7925664944b72c7261291a350745.png)](https://gyazo.com/755e7925664944b72c7261291a350745)

It seems that `shx` does not support running bash files. However, it's Github page says:
> * ShellJS: Good for writing long scripts, all in JS, running via NodeJS (e.g. node myScript.js).
> * shx: Good for writing one-off commands in npm package scripts (e.g. "clean": "shx rm -rf out/").

Maybe changing this script into a ShellJS scripts would resolve this issue?

**Comment by AaronCoplan** [comment]
@Thomas-Smyth I agree - good call!  I will try porting the script to ShellJS tonight and will create a PR.

**Comment by Thomas-Smyth** [comment]
Whilst on the topic of flow, got any ideas on the cause of this:

`On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 265 characters. Skipping E:\thoma\Documents\Development\OS Contributions\tabler-react\example\node_modules\tabler-react\example\node_modules\babel-preset-react-app\node_modules\@babel\plugin-syntax-object-rest-spread\node_modules\@babel\core\lib\transformation\util\missing-plugin-helper.js`

It seems that flow is recursively going into the `tabler-react` link in the example until my path length is exceeded.

**Comment by jonthomp** [comment]
I'm closing this as the proposal for version 2 moves us away from `flow`, plus these issues should get picked up once we make progress on #350 (I'll point to this issue there too)
