### ISSUE TITLE
Is it possible to use the Form.Input with Redux-Form?

### ISSUE THREAD

**Issue by NickAlvesX** [tabler/tabler-react#403]
I tried something like:

```
<Field
    label='email'
    name={'email'}
    component={Form.Input}
/>
```

But this doesn't seems to work. Is there any way? Because in documentation I have seen in the Login Page component saying that "Can be easily wrapped with form libraries like formik and redux-form". How?

**Comment by NickAlvesX** [comment]
I'm working with this workaround while it has no answers.

`import React, { Component } from 'react';
import {Form} from 'tabler-react';
import PropTypes from 'prop-types';

export default class Input extends Component {
    render() {
        const {
            input: { value, onChange }
        } = this.props;

        return <Form.Input {...this.props} value={value} onChange={value => onChange(value)}/>;
    }
}

Input.propTypes = {
    input: PropTypes.object
};
`

`<Field
    name={'name'}
    component={Input}
/>`

**Comment by jonthomp** [comment]
Sorry I'm afraid there isn't at the moment, working on this as part of version 2

**Comment by jonthomp** [comment]
These are now implemented as part of v2.
