### ISSUE TITLE
Avatar component does not have fallback for incorrect/unreachable URL

### ISSUE THREAD

**Issue by SoorajSethumadhavan** [tabler/tabler-react#404]
The Avatar component should have a fallback onError support if the remote url referred in the imageURL does not work.
OR
The placeholder should work as fallback if the imageURL fails.

**Comment by SoorajSethumadhavan** [comment]
Any updates on this??

**Comment by SoorajSethumadhavan** [comment]
Hi,
I am a newbie to react and JS in general... I was checking out the code in Avatar.react.js. 
`<span
      className={classes}
      style={
        imageURL
          ? Object.assign(
              {
                backgroundImage: `url(${imageURL})`,
              },
              style
            )
          : style
      }
      onClick={onClick}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={onPointerEnter}
      onPointerLeave={onPointerLeave}
    >`

instead of this, why can't we have <img> tag and handle the unavailability of the image from url with onError...
if the image is not available, then the Initials of the user should be rendered.. (get initials from the name passed in 'name' attribute..
[https://github.com/Sitebase/react-avatar](url) these guys have done it seamlessly..

Please help me out here..

**Comment by jonthomp** [comment]
I think it makes the most sense for you to just https://github.com/Sitebase/react-avatar in this situation.
