### ISSUE TITLE
The dropdown component does not work

### ISSUE THREAD

**Issue by zabaala** [tabler/tabler-react#406]
On the documentation site itself, the dropdown does not work. I still tried to apply it to my project, but I did not succeed. Only AccountDropdown worked.

Is there anything wrong with the component or the documentation?

**Comment by AaronCoplan** [comment]
I'm going to close this for now as I think that should work until we get the "children" prop to work.  Feel free to comment to let me know if I'm wrong or if you're still having trouble and I'll reopen the issue.
