### ISSUE TITLE
Add inputRef to Form.Input

### ISSUE THREAD

**Issue by NickAlvesX** [tabler/tabler-react#414]
That's crucial to use it with libraries like `react-text-mask`.

**Comment by jonthomp** [comment]
Does the [FormMaskedInput](http://tabler-react.com/documentation/#formmaskedinputreact) component cover your use case?

**Comment by jonthomp** [comment]
Version 2 is now forwarding `ref` to the `input` component

**Comment by vivek-reddy-7** [comment]
> Version 2 is now forwarding `ref` to the `input` component

`ref.current` is still `null`. Isn't the version still 1.xx? can you explain how to solve this issue?
