### ISSUE TITLE
Invalid DOM property `minlength`. Did you mean `minLength`

### ISSUE THREAD

**Issue by essaricy** [tabler/tabler-react#434]
Getting couple of warnings when using Form.Input elements. Below are some
Invalid DOM property `minlength`. Did you mean `minLength`?
Invalid DOM property `maxlength`. Did you mean `maxLength`?

Looks like an issue with case-sensitive

**Comment by preethamntp** [comment]
Getting these message while using forms
Warning: Invalid DOM property `minlength`. Did you mean `minLength`?
    in input (created by Form.Input)
    in Form.Input (created by FormTextInput)
Warning: Invalid DOM property `maxlength`. Did you mean `maxLength`?
    in input (created by Form.Input)
    in Form.Input (created by FormTextInput)
