### ISSUE TITLE
multiple select in form.select 

### ISSUE THREAD

**Issue by yash2code** [tabler/tabler-react#443]
How can I use Form.Select so that one can select multiple options from the dropdown.

` <Form.Select
            label="Time Slots"
            name="timeslots"
            onChange={this.handleChange}
          >
            <option key="all" value="all">
              All{" "}
            </option>
            {slots.map(e => {
              return (
                <option key={e.value} value={e.value}>
                  {e.label}
                </option>
              );
            })}
          </Form.Select>`

**Comment by jonthomp** [comment]
The `multiple` prop has been added in v1.30.1
