### ISSUE TITLE
How to use tabler theme in my Web site?

### ISSUE THREAD

**Issue by Xumochuan** [tabler/tabler-react#460]
Hi.
Thanks for your amazing React component.
I wanna develop react js app with my business.
I want to use header and menu same as Tabler Template.

![header_menu](https://user-images.githubusercontent.com/47884397/58754411-f39b1800-8501-11e9-9eba-d902b9934ced.png)

How can I do?
Hope your kind help.

Sincerely

**Comment by hasansan07** [comment]
@Xumochuan please check Sitewrapper component in example folder of the repo.

**Comment by Xumochuan** [comment]
Hello
Thanks for your kind contact.
I have tried above method that you attached and I get some result.

![improvement](https://user-images.githubusercontent.com/47884397/58754948-c43dd880-850c-11e9-8386-2fc6398acf2d.png)

Could you do me a favor to get improvement my project?
Thanks again :)
