### ISSUE TITLE
Expose underlying controls in components?

### ISSUE THREAD

**Issue by elucidsoft** [tabler/tabler-react#464]
Is there a way to expose the underlying controls in components or to inject in properties to the html elements? For instance on the Forms component I would like to be able to disable them under certain conditions by passing in disabled attribute to the underlying html element. But I don't see a way to currently do that?  I was going to add the prop for disabled, but would it make sense to be able to inject these attributes into these attributes in instead so you can get complete flexibility to do whatever you want?  Thoughts?

**Comment by jonthomp** [comment]
@elucidsoft there was originally a decision made to not spread any additional props to the underlying components, this has caused several issues along the way but is something I'm removing in version 2. So I guess the answer to your question is, watch this space!

**Comment by jonthomp** [comment]
This is now done for `form` related components and some others on v2 branch
