### ISSUE TITLE
font awesome icon not working in nav icon

### ISSUE THREAD

**Issue by jkunwar** [tabler/tabler-react#465]
i added prefix fa for font awesome also included font awesome cdn, but font awesome did not work on nav icon

**Comment by jonthomp** [comment]
@jkunwar please could you provide some example code or a link to a working example?

**Comment by jkunwar** [comment]
https://github.com/jkunwar/tabular-react-test

here is the sample repo. I copied SiteWrapper file from demo and added **fa** prefix in navitem array but there is still  **fe** prifix

**Comment by jonthomp** [comment]
Thanks @jkunwar, unfortunately, it's not currently supported. The WIP version 2 solves this
