### ISSUE TITLE
Grid/Table Pagination

### ISSUE THREAD

**Issue by gucarletto** [tabler/tabler-react#539]
I can't seen to find examples or documentation on pagination of grids, like this from tabler.io:
![image](https://user-images.githubusercontent.com/1106206/94600857-f0847900-0268-11eb-80f9-46ddacca0e78.png)

Is this really not implemented or am I just not finding? If it's the latter can anyone point me where to find it?

**Comment by JimmyKho** [comment]
Hi @gucarletto, I'm looking for the pagination component too. Seems like its not available in the tabler-react version yet.

**Comment by gucarletto** [comment]
Created the component manually
