### ISSUE TITLE
Build blog card component

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#62]
Assigned to @KhaldiAmer 

See https://tabler.github.io/tabler/blog.html
![screenshot from 2018-04-28 21-29-39](https://user-images.githubusercontent.com/660222/39400595-4a6eafaa-4b2b-11e8-9dd5-c09ffa6675fc.png)

**Comment by KhaldiAmer** [comment]
Can I take this one too?

**Comment by jonthomp** [comment]
@KhaldiAmer we're sticking to one at a time how now just in case but I doubt anyone will take this by the time you finish the other :)

**Comment by KhaldiAmer** [comment]
Can I take this one now? 😄
