### ISSUE TITLE
Build store product card component

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#63]
Assigned to @KhaldiAmer 

https://tabler.github.io/tabler/store.html

![screenshot from 2018-04-28 19-22-21](https://user-images.githubusercontent.com/660222/39399647-8307a55e-4b19-11e8-8b02-b54db76d5656.png)

**Comment by KhaldiAmer** [comment]
Can I take this?

**Comment by jonthomp** [comment]
Close by https://github.com/tabler/tabler-react/pull/93
