### ISSUE TITLE
Build store demo page

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#64]
Replicate the [tabler store demo page](https://tabler.github.io/tabler/store.html) in our example site

Will need https://github.com/tabler/tabler-react/issues/63 to be completed first.

**Comment by KhaldiAmer** [comment]
Worked on this in PR #93.

**Comment by jonthomp** [comment]
@KhaldiAmer have you worked on the Table part of the store demo page at all? If not happy if jump on it now?

**Comment by KhaldiAmer** [comment]
Pushed!
