### ISSUE TITLE
Blog demo page

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#72]
Replicate the [blog demo page](https://tabler.github.io/tabler/blog.html),

Requires https://github.com/tabler/tabler-react/issues/62

Assigned to @MrJarv1s

**Comment by iamzjohn** [comment]
Is someone assigned to this one?

**Comment by AaronCoplan** [comment]
@iamzjohn I don't believe so!  Would you like me to indicate it as assigned to you?

**Comment by iamzjohn** [comment]
@AaronCoplan I can do it, but as I see the Blog Card isn't  done yet, When finished I can take this. And I might help on the Blog Card First

**Comment by MrJarv1s** [comment]
@iamzjohn the Blog Card has been implemented, do you still want to take care of this one?

**Comment by MrJarv1s** [comment]
@jonthomp Please assign me to this one
