### ISSUE TITLE
Add a simple date component

### ISSUE THREAD

**Issue by jonthomp** [tabler/tabler-react#77]
Create an easy to use date component, using our existing base components where possible, for collecting dates like the date of birth component [here](https://tabler.github.io/tabler/form-elements.html)

![screenshot from 2018-04-29 19-26-49](https://user-images.githubusercontent.com/660222/39409675-5543f2e2-4be3-11e8-9e1f-a9474a0c0391.png)

**Assigned to:** @hugo-fonseca

**Comment by hugo-fonseca** [comment]
Hey, first time here, loved to see tabler fully ported to react!

I can take this if it's still available! 👍

**Comment by AaronCoplan** [comment]
@hugo-fonseca Awesome!  I'll mark it as assigned to you 👍
