### ISSUE TITLE
Removing / using eslint?

### ISSUE THREAD

**Issue by AaronCoplan** [tabler/tabler-react#9]
Are we using eslint for anything?  Since we are using prettier, I'm not sure if ES lint is serving any other purpose - I may be wrong though.  If we are not using it that would really clean up our package.json file.

**Comment by jonthomp** [comment]
What's there at the moment just came from the initial setup, I was thinking maybe keep it but change to match what is used in create-react-app, they've got a nice baseline that would help keep to a code style especially if we get a lot of contributors?

**Comment by AaronCoplan** [comment]
Ok cool - I'll leave that for you to do then
